name: qaser_user
description: A new Flutter project.
publish_to: 'none'

version: 2.0.75+24


environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get:
  flutter_otp_text_field:
  jiffy:
  http: ^1.1.0
  cached_network_image_plus:
  google_maps_flutter:
  geolocator:
  auto_size_text: ^3.0.0
  geocoding:
  firebase_messaging:
  firebase_core:
  path:
  url_launcher:
  package_info_plus: ^5.0.1
  dartz:
  image_picker:
  lottie:
  firebase_analytics:
  string_capitalize: ^0.0.10
  badges: ^3.1.1
  freezed_annotation: ^2.4.1
  rating_dialog: ^2.0.4
  flutter_swiper_view: ^1.1.8
  dropdown_button2: ^2.3.8
  icon_broken:
  animated_text_kit: ^4.2.2
  connectivity_plus: ^5.0.2
  flutter_smart_dialog: ^4.9.4
  dotted_dashed_line: ^0.0.3
  animated_flip_counter: ^0.2.6
  flutter_dotenv: ^5.1.0
  device_info_plus: ^9.1.0
  json_serializable:
  get_storage: ^2.1.1
  json_annotation: ^4.8.1
  icons_plus:
  awesome_notifications:
  flutter_expandable_fab: ^2.0.0
  firebase_crashlytics: ^3.4.8
  insta_image_viewer:
  animated_number: ^1.0.2
  timer_builder: ^2.0.0
  pretty_qr_code: ^3.0.0
  upgrader: ^8.4.0
  encrypt: ^5.0.2





dev_dependencies:
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  dependency_validator:
  flutter_launcher_icons: ^0.13.1




flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon_ramadan.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf
          weight: 700


  assets:
    - assets/lottie/
    - assets/images/
    - assets/
    - .env
    - assets/fonts/Almarai/
