// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-UyXTKBpMEZTBuu2gQ0Cs1Pw_DyVF-vU',
    appId: '1:164161370503:android:1f42194c102fd2f7befb22',
    messagingSenderId: '164161370503',
    projectId: 'qaser-sharqi',
    storageBucket: 'qaser-sharqi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ_QhvFsE3V3svqzlBghigMntrcu3q_qY',
    appId: '1:164161370503:ios:bfc706859d06bf08befb22',
    messagingSenderId: '164161370503',
    projectId: 'qaser-sharqi',
    storageBucket: 'qaser-sharqi.appspot.com',
    androidClientId: '164161370503-839aen8kg925j342pfh1f6pnap6q9rm6.apps.googleusercontent.com',
    iosClientId: '164161370503-uqkv0h6v0m0eb1nf58u1ejk0hu6p5jd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.qaserUser',
  );
}
